export const GalleryData = [
  {
    id: 1,
    image: "./assests/Gallery/gallery3.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 2,
    image: "./assests/Gallery/gallery3.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 3,
    image: "./assests/Gallery/gallery4.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 4,
    image: "./assests/Gallery/gallery5.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 5,
    image: "./assests/Gallery/gallery6.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 6,
    image: "./assests/Gallery/gallery7.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 7,
    image: "./assests/Gallery/gallery8.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 8,
    image: "./assests/Gallery/gallery9.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 9,
    image: "./assests/Gallery/gallery10.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 10,
    image: "./assests/Gallery/gallery2.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 11,
    image: "./assests/Gallery/gallery2.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 12,
    image: "./assests/Gallery/gallery3.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 13,
    image: "./assests/Gallery/gallery4.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 15,
    image: "./assests/Gallery/gallery5.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 16,
    image: "./assests/Gallery/gallery6.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 17,
    image: "./assests/Gallery/gallery7.jpg",
    event: "Education",
    purpose: "Charity",
  },
  {
    id: 18,
    image: "./assests/Gallery/gallery8.jpg",
    event: "Children",
    purpose: "Charity",
  },
  {
    id: 19,
    image: "./assests/Gallery/gallery9.jpg",
    event: "Blood",
    purpose: "Charity",
  },
  {
    id: 20,
    image: "./assests/Gallery/gallery10.jpg",
    event: "Education",
    purpose: "Charity",
  },
];
