import React from "react";
import { MdLocationOn, MdAccessTimeFilled } from "react-icons/md";
export const Eventdata = [
  {
    id: 1,
    image: "./assests/event1.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 2,
    image: "./assests/event2.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 3,
    image: "./assests/event3.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 4,
    image: "./assests/event4.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 5,
    image: "./assests/event5.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 6,
    image: "./assests/event6.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 7,
    image: "./assests/event7.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
  {
    id: 8,
    image: "./assests/event5.jpg",
    date: "23 December, 2022",
    time: "8:00pm",
    location: "Gaya",
    title: "Save Trees, Save Planet",
    icon1: <MdLocationOn />,
    icon2: <MdAccessTimeFilled />,
  },
];
